#
# Module manifest for module "Todo"
#
# Generated by: Stefan Greve
#
# Generated on: 2/19/2022
#

@{
    RootModule = "Todo.psm1"
    ModuleVersion = "1.1.1"
    CompatiblePSEditions = @("Desktop")
    GUID = "1005fb56-c909-4fd8-87db-0d6d57de726c"
    Author = "Stefan Greve"
    CompanyName = "Advanced Systems"
    Copyright = "(c) 2022 Advanced Systems. All rights reserved."
    Description = "PowerShell Module to manage your TODO list from the terminal."
    PowerShellVersion = "5.1"
    RequiredModules = @("SQLite")
    FormatsToProcess = @("TaskTable.ps1xml")

    FunctionsToExport = @(
        "New-TodoList",
        "Get-TodoList",
        "Remove-TodoList",
        "New-Task",
        "Update-Task",
        "Remove-Task"
    )

    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @(
        "ntodo", # New-TodoList
        "gtodo", # Get-TodoList
        "rtodo", # Remove-TodoList
        "ntask", # New-Task
        "utask", # Update-Task
        "rtask"  # Remove-Task
    )

    FileList = @(
        "Todo.psd1",
        "Todo.psm1",
        "TaskTable.ps1xml",
        "classes\Task.ps1",
        "public\Get-TodoList.ps1",
        "public\New-Task.ps1",
        "public\New-TodoList.ps1",
        "public\Remove-Task.ps1",
        "public\Remove-TodoList.ps1",
        "public\TodoList.sql",
        "public\Update-Task.ps1"
    )

    PrivateData = @{
        PSData = @{
            Tags = @("PSEdition_Desktop", "Windows", "Todo", "Productivity")
            LicenseUri = "https://www.gnu.org/licenses/gpl-3.0.en.html"
            ProjectUri = "https://github.com/Advanced-Systems/todo"
            ReleaseNotes = "https://github.com/Advanced-Systems/todo/blob/master/CHANGELOG.md"
        }
    }
}
